select * from [dbo].[customer_shopping_behavior_cleaned]

---Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue 
from [dbo].[customer_shopping_behavior_cleaned]
group by gender

---Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from [dbo].[customer_shopping_behavior_cleaned]
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from [dbo].[customer_shopping_behavior_cleaned])

---Q3. Which are te top 5 products with the highest average review ratings?
select top 5
    item_purchased,
    AVG(review_rating) as average_rating
from[dbo].[customer_shopping_behavior_cleaned]
group by item_purchased
order by average_rating desc;

---Q4. Compare the average purchase amount between standard and express shipping. 
select shipping_type,
AVG(purchase_amount) as Avg_purchase
from[dbo].[customer_shopping_behavior_cleaned]
where shipping_type in ('Standard', 'Express')
group by shipping_type;

---Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscriers.
select subscription_status,
count (customer_id) as total_customers,
round(AVG(purchase_amount),2) as Avg_spend,
round(sum(purchase_amount),2) as Total_revenue
from [dbo].[customer_shopping_behavior_cleaned]
group by subscription_status
order by Total_revenue, Avg_spend;

---Q6. Which 5 products have the highest percentage of purchases with discount applied?
select top 5 
    item_purchased,
round(100 * sum (case when discount_applied = 'Yes' then 1 else 0 end) / COUNT(*), 2) as discount_percentage
from [dbo].[customer_shopping_behavior_cleaned]
group by item_purchased
order by discount_percentage desc;

---Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from [dbo].[customer_shopping_behavior_cleaned] 
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

---Q8. What are the top 3 most purchased products within each category?
WITH RankedProducts as (
    select 
        category,
        item_purchased,
        sum(customer_id) as total_purchased,
        DENSE_RANK() over (partition by category order by sum(customer_id) desc) as rank_id
    from [dbo].[customer_shopping_behavior_cleaned]
    group by category, item_purchased
)
select
     category,
     item_purchased,
     total_purchased
from RankedProducts
where rank_id <= 3;

---Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from [dbo].[customer_shopping_behavior_cleaned]
where previous_purchases > 5
group by subscription_status;

---Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from[dbo].[customer_shopping_behavior_cleaned]
group by age_group
order by total_revenue desc;